# Generated by Django 4.1.6 on 2023-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETD', models.DateTimeField()),
                ('contracts', models.CharField(blank=True, default='', max_length=16)),
                ('car_number', models.CharField(blank=True, default='', max_length=10)),
                ('key', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
