# Generated by Django 4.1.6 on 2023-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginformation',
            name='ETD',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
